### ISSUE TITLE
用户名中包含特殊符号抛出异常

### ISSUE THREAD

**Issue by devqin** [tvrcgo/weixin-redpack#2]
Exception while invoking method 'sendRedPack' Error: Invalid character (�) in string: Arthur-诚信🔥 at index 9
     at XMLStringifier.module.exports.XMLStringifier.assertLegalChar (*/bundle/programs/server/npm/node_modules/weixin-redpack/node_modules/xmlbuilder/lib/XMLStringifier.js:149:15)
     at XMLStringifier.assertLegalChar (*/bundle/programs/server/npm/node_modules/weixin-redpack/node_modules/xmlbuilder/lib/XMLStringifier.js:4:59)
     at XMLStringifier.module.exports.XMLStringifier.eleText (*/bundle/programs/server/npm/node_modules/weixin-redpack/node_modules/xmlbuilder/lib/XMLStringifier.js:28:19)
     at new XMLText (*/bundle/programs/server/npm/node_modules/weixin-redpack/node_modules/xmlbuilder/lib/XMLText.js:19:35)
     at XMLElement.module.exports.XMLNode.text (*/bundle/programs/server/npm/node_modules/weixin-redpack/node_modules/xmlbuilder/lib/XMLNode.js:165:15)
     at XMLElement.module.exports.XMLNode.node (*/bundle/programs/server/npm/node_modules/weixin-redpack/node_modules/xmlbuilder/lib/XMLNode.js:157:15)
     at XMLElement.module.exports.XMLNode.element (*/bundle/programs/server/npm/node_modules/weixin-redpack/node_modules/xmlbuilder/lib/XMLNode.js:100:28)
     at XMLElement.module.exports.XMLNode.ele (*/bundle/programs/server/npm/node_modules/weixin-redpack/node_modules/xmlbuilder/lib/XMLNode.js:268:19)
     at */bundle/programs/server/npm/node_modules/weixin-redpack/node_modules/xml2js/lib/xml2js.js:204:37
     at Builder.exports.Builder.Builder.buildObject (*/bundle/programs/server/npm/node_modules/weixin-redpack/node_modules/xml2js/lib/xml2js.js:216:14)

**Comment by devqin** [comment]
closed by https://github.com/tvrcgo/weixin-redpack/pull/3
